In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
y = torch.rand(5, 3)
print(y)

tensor([[0.8380, 0.2493, 0.4443],
        [0.3022, 0.6493, 0.9635],
        [0.7066, 0.1384, 0.5057],
        [0.5487, 0.1893, 0.9705],
        [0.6019, 0.5864, 0.8319]])


In [4]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8380, 0.2493, 0.4443],
        [0.3022, 0.6493, 0.9635],
        [0.7066, 0.1384, 0.5057],
        [0.5487, 0.1893, 0.9705],
        [0.6019, 0.5864, 0.8319]])


In [5]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [6]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!